//! Leptos-фронтенд Шеш-Беш: вся игровая логика — движок `sheshbesh` в WASM.
//! Доска — векторная (SVG); фишки рисуются отдельным слоем keyed-кружков, что даёт
//! плавную анимацию перемещения (CSS-переход `cx`/`cy`). Перед партией — экран
//! настроек (2/3/4 игрока, тип каждой стороны: человек/компьютер). Ход человека
//! собирается кликами (фишка → клетка) по одной кости; компьютерные стороны ходят
//! сами (эвристика).

leptos_i18n::declare_locales! {
    interpolate_display,
    default: "ru",
    locales: ["ru", "en"],
    ru: {
        // Locale
        locale_ru: "Русский",
        locale_en: "English",
        // Theme
        theme_midnight: "Полночь",
        theme_dusk: "Сумерки",
        theme_daylight: "Рассвет",
        theme_forest: "Лес",
        // Speed
        speed_vslow: "Очень медленно",
        speed_slow: "Медленно",
        speed_normal: "Обычная",
        speed_fast: "Быстро",
        speed_vfast: "Очень быстро",
        // Algo
        algo_mlp: "MLP",
        algo_search: "MLP+поиск",
        algo_linear: "Linear",
        algo_heuristic: "Эвристика",
        // Title
        app_title: "Шеш-Беш",
        // Settings
        settings_players: "Игроков:",
        settings_side: "Сторона {{ letter }}",
        settings_human: "Человек",
        settings_computer: "Компьютер",
        settings_mode: "Режим:",
        settings_teams: "Команды 2×2",
        settings_ffa: "Каждый сам",
        settings_start: "Начать игру",
        settings_rules: "📖 Правила",
        settings_tutorial: "🎓 Обучение",
        settings_about: "❤️ От автора",
        settings_lang: "Язык / Language",
        settings_dev: "Режим разработчика",
        // Controls
        speed_name: "Скорость:",
        theme_title: "Тема оформления",
        // Hamburger
        hamburger_rules: "📖 Правила",
        hamburger_sound: "Звук",
        hamburger_speed: "Скорость",
        hamburger_theme: "Тема",
        hamburger_keys: "⌨ Горячие клавиши",
        hamburger_log: "📋 Лог партии",
        hamburger_lang: "🌐 Язык",
        hamburger_menu: "Меню",
        // Herald / game
        herald_game_on: "Игра началась! Ходит {{ who }}.",
        herald_roll: "{{ who }} бросает кости…",
        herald_no_move: "{{ who }}: выпало {{ a }} и {{ b }}. Ходить нечем — пропуск.",
        herald_wait_move: "{{ who }}: выпало {{ a }} и {{ b }}. Выберите ход.",
        herald_ai_thinking: "{{ who }}: выпало {{ a }} и {{ b }}. Идёт выбор хода…",
        herald_double: "{{ who }}: выпало {{ a }} и {{ b }}. Дубль — ещё ход!",
        // Burn
        burn_double: "{{ who }}: сыграть {{ n }} больше нечем — дубль, переброс!",
        burn_pip: "{{ who }}: сыграть {{ n }} нечем — кость сгорает.",
        // Forced reply
        forced_reply: "{{ who }}: обязательный ход на 6 после выкупа.",
        forced_pick_msg: "{{ who }}: выберите обязательный ход на 6 после выкупа.",
        // Move notes
        note_capture: "{{ who }} съедает фишку: {{ victim }}!",
        note_finish: "{{ who }}: все фишки в Доме — финиш!",
        note_ransom: "{{ who }}: выкуп пленной фишки.",
        note_enter: "ввод фишки в игру.",
        note_moon_enter: "фишка взлетает на Луну!",
        note_moon_advance: "продвижение по дорожке Луны.",
        note_moon_exit: "сход с Луны.",
        note_prison_enter: "фишка угодила в Тюрьму!",
        note_prison_release: "выход из Тюрьмы.",
        note_home_enter: "заход фишки в Дом!",
        note_home_advance: "фишка идёт вглубь Дома.",
        // Side name
        side_human: "Игрок",
        side_ai: "ИИ",
        // Result
        result_team_wins: "Команда {{ team }} победила! Игра окончена.",
        result_full: "Победил {{ who }}! Места: {{ places }}.",
        // Demo
        demo_reserve: "Резерв (старт)",
        demo_moon_1: "16 фишек на Луне — поле 1",
        demo_moon_3: "16 фишек на Луне — поле 3",
        demo_moon_6: "16 фишек на Луне — поле 6",
        demo_cell: "16 фишек на углу",
        demo_prison: "16 фишек в одной Тюрьме",
        demo_prison_stack: "Тюрьма: стопки одного цвета",
        demo_captured: "12 фишек в плену (макс)",
        demo_homes: "Дома заполнены",
        demo_anim: "▶ Анимация: ход и съедание",
        demo_home_test: "🏠 Тест: вход в Дом (клик)",
        demo_complete: "Демо завершено.",
        // Dev
        dev_title: "Режим разработчика: выберите сценарий.",
        dev_sounds: "Звуки:",
        dev_back: "Настройки",
        // Sound labels
        sound_dice: "🎲 Бросок",
        sound_enter: "⬇ Ввод",
        sound_capture: "💥 Съедание",
        sound_prison_in: "🔒 В Тюрьму",
        sound_prison_out: "🔓 Из Тюрьмы",
        sound_moon: "🌙 Луна",
        sound_ransom: "💰 Выкуп",
        sound_home: "🏠 Дом",
        sound_win: "🏆 Победа",
        // Game UI
        game_pause: "Пауза",
        game_resume: "Продолжить",
        game_stop: "Закончить игру",
        game_keys_title: "Горячие клавиши хода",
        game_keys_tab: "следующая фишка",
        game_keys_1_2: "ход меньшей / большей костью",
        game_keys_3: "обе кости выбранной фишкой",
        game_keys_i: "ввести фишку из резерва",
        game_keys_r: "выкупить пленную фишку",
        game_log_title: "Лог партии",
        game_log_hint: "Клик по тексту — выделить всё, затем Ctrl/Cmd+C",
        game_log_close: "Закрыть",
        // About page
        about_title: "От автора",
        about_p1: "Эта настольная игра ещё в 70-е годы была известна среди студентов МИФИ под названием «Шеш-Беш», «Шиш-Беш» или просто «Шишка». Мой отец играл в неё с одногруппниками.",
        about_p2: "В 90-е годы я был маленьким и в один из дней мы с отцом купили в книжном магазине лист ватмана и он расчертил на нём поле. Мы стали играть вечерами, сидя на ковре. К ним присоединялись его школьные и студенческие друзья. Было здорово.",
        about_p3: "Вспоминая эти моменты с теплотой, я решил воссоздать игру на компьютере.",
        about_p4: "Упоминаний этого варианта игры в Интернете мне найти так и не удалось, находил лишь похожую настолку под названием «Шеш-Беш», но выглядит она несколько иначе: поле в виде креста, без Луны и Тюрьмы.",
        // Rules page
        rules_title: "Шеш-Беш — правила",
        rules_lead: "Самобытный вариант нард. Играют вдвоём (противоположные стороны) или вчетвером; каждый владеет одной стороной квадрата и её Домом. Вчетвером можно играть командами 2×2 (союзники — противоположные стороны) или каждый сам за себя (FFA).",
        rules_goal_title: "Цель",
        rules_goal_text: "Провести все 4 свои фишки полный круг по доске (против часовой стрелки) и завести их в свой Дом. Чужие фишки в Дом попасть не могут. Вдвоём победил тот, кто первым собрал Дом. В командах 2×2 победа, когда обе стороны команды завели все фишки. В FFA партия идёт, пока не финишируют все, кроме одного (последний — проигравший).",
        rules_first_title: "Право первого хода",
        rules_first_text: "Активные стороны по очереди кидают кости; начинает тот, кто первым выбросил 6.",
        rules_board_title: "Доска",
        rules_board_l1: "Квадрат; у каждой из 4 сторон — 19 клеток (углы общие для двух сторон). Против часовой стрелки.",
        rules_board_l2: "Посередине каждой стороны — Дом из 4 клеток, идущих внутрь квадрата.",
        rules_board_l3: "Все фишки стартуют в резерве у своего Дома и вводятся в игру.",
        rules_move_title: "Ход",
        rules_move_l1: "За ход бросают две кости. Значения можно отнести к двум разным фишкам (по значению на каждую) или объединить на одну («в один мах»).",
        rules_move_l2: "«Выбросить число» всегда значит значение на одной кости, а не сумму.",
        rules_move_l3: "Объединять кости можно только при ходе по периметру. Для спец-действий (ввод, выкуп, Луна, Тюрьма, Дом) нужна ровно одна кость нужного значения.",
        rules_move_l4: "Ввод фишки в игру — по 6. На точку входа нельзя поставить вторую свою фишку; чужую там можно съесть.",
        rules_move_l5: "Дубль даёт право на ещё один полный ход.",
        rules_move_l6: "Правило максимального хода: из вариантов выбирают тот, что использует больше очков (в идеале — все).",
        rules_move_l7: "Нельзя проходить через занятые клетки — исключение только углы (через занятый угол проходить можно). Свою и чужую фишку на пути перешагнуть нельзя.",
        rules_special_title: "Особые клетки",
        rules_special_l1: "Луна (2-я клетка от угла) — короткий путь. Фишка улетает на внутреннюю дорожку полей 1·3·6: с «1» на «3», с «3» на «6», с «6» обратно на доску (на 2-ю клетку от следующего угла). Если на выходе стоит чужая фишка, она съедается. Луна полностью безопасна (и вход, и дорожка). Чужие Луны срезают путь вперёд, своя Луна (у самого Дома) выбрасывает фишку в начало круга — это второй круг.",
        rules_special_l2: "Тюрьма (4-я клетка от угла) — изолирует фишку: выйти можно только выбросив 4 (фишка освобождается и остаётся на месте, никуда не продвигаясь). Удобно блокировать чужие фишки. Фишка попадает в Тюрьму, только если клетка Тюрьмы — конечная цель хода; если лишь перешагивает её (объединённый ход или большая кость), Тюрьма не срабатывает. Пленник внутри Тюрьмы не мешает проходу — перекрывает клетку только освобождённая фишка, стоящая на ней.",
        rules_special_l3: "Углы — общие клетки; на них фишки не едят друг друга, и через занятый угол можно проходить.",
        rules_capture_title: "Съедание, плен и выкуп",
        rules_capture_l1: "Встав на клетку с чужой фишкой, вы её съедаете — она попадает к вам в плен. В командах 2×2 союзники не едят друг друга.",
        rules_capture_l2: "Съедания нет на углах, Луне и в Тюрьме.",
        rules_capture_l3: "Чтобы вернуть пленную фишку, нужно выбросить 6 (выкуп). Соперник не вправе отказать — он обязан сделать ответный ход на 6 клеток (если есть легальный ход на 6; иначе — пропуск). После этого нужна ещё одна 6 для повторного ввода фишки.",
        rules_home_title: "Дом",
        rules_home_text: "Заход в Дом — ровно по броску, по одной фишке в клетку; перепрыгивать занятые клетки Дома нельзя (но фишка в Доме может идти глубже, освобождая место). Перебор за пределы Дома нелегален. Второй круг возможен через Луну: своя Луна стоит у самого Дома, и фишка с неё выходит в начало круга — приходится идти ещё один полный круг.",
        // Tutorial
        lesson_title_1: "Цель и ввод",
        lesson_text_1: "У каждого 4 фишки в резерве; цель — обойти доску против часовой и собрать все в своём Доме. Выпало 6 и 5: по 6 фишка входит на точку входа, затем оставшейся 5 доходит до Тюрьмы. Нажмите фишку, затем клетку (по одной кости), или ▶.",
        lesson_title_2: "Тюрьма и Луна",
        lesson_text_2: "Тюрьма держит фишку: выйти можно только выбросив 4 — она выпала. Затем оставшейся 6 фишка идёт дальше и попадает на Луну. Сделайте оба под-хода.",
        lesson_title_3: "Луна",
        lesson_text_3: "Луна — короткий безопасный путь по полям 1·3·6 (съесть нельзя). Выпало 1 — переход с поля «1» на «3». Вторая кость (2) не играется: на Луне нужно точное значение. Сделайте ход.",
        lesson_title_4: "Дорожка Луны",
        lesson_text_4: "Выпало 3 — переход с поля «3» на «6». Осталось выбросить 6, чтобы сойти с Луны.",
        lesson_title_5: "Сход с Луны",
        lesson_text_5: "По 6 фишка сходит с Луны на доску, заметно ближе к Дому. Впереди — фишка соперника.",
        lesson_title_6: "Съедание",
        lesson_text_6: "Встав на клетку с фишкой соперника, фишка съедает её — пленная уходит к нашему Дому (с красной обводкой). На углах, Луне и в Тюрьме не едят.",
        lesson_title_7: "Плен и выкуп",
        lesson_text_7: "Чтобы вернуть пленную фишку, её владелец выбрасывает 6 — она возвращается в резерв (выкуп). Соперник тут же выкупает свою фишку (она улетает к нему в резерв). Тогда захватчик обязан сразу сходить на 6 клеток: выберите, какой нашей фишкой — нажмите фишку, затем подсвеченную клетку.",
        lesson_title_8: "Дом и победа",
        lesson_text_8: "Дойдя до Дома, фишка заходит ровно по броску — по одной в клетку; перепрыгивать занятые клетки Дома нельзя (но можно идти глубже). Чужие фишки в Дом не пускают. Заведите фишку в Дом этим ходом — все 4 фишки дома, и вы выиграли!",
        // Tutorial hints
        tutorial_hint_roll: "🎲 Бросаем кости…",
        tutorial_hint_opp_roll: "🎲 Противник бросает кости…",
        tutorial_hint_move: "👆 Сделайте ход сами: нажмите на фишку, затем на подсвеченную клетку. Или жмите ▶.",
        tutorial_hint_ransom: "👆 Выберите, какой фишкой сделать обязательный ход на 6: нажмите фишку, затем её клетку.",
        tutorial_lesson: "Шаг обучения",
        tutorial_back: "Назад в меню",
        tutorial_prev: "◀ Назад",
        tutorial_next: "Далее",
        // Home test
        home_test_herald: "Тест входа в Дом: клетка входа (ворота) — обычная клетка, на ней можно остановиться (Step); заход в Дом — отдельным ходом, по клетке Дома внутри.",
    },
    en: {
        // Locale
        locale_ru: "Russian",
        locale_en: "English",
        // Theme
        theme_midnight: "Midnight",
        theme_dusk: "Dusk",
        theme_daylight: "Daylight",
        theme_forest: "Forest",
        // Speed
        speed_vslow: "Very Slow",
        speed_slow: "Slow",
        speed_normal: "Normal",
        speed_fast: "Fast",
        speed_vfast: "Very Fast",
        // Algo
        algo_mlp: "MLP",
        algo_search: "MLP+Search",
        algo_linear: "Linear",
        algo_heuristic: "Heuristic",
        // Title
        app_title: "Shesh-Besh",
        // Settings
        settings_players: "Players:",
        settings_side: "Side {{ letter }}",
        settings_human: "Human",
        settings_computer: "Computer",
        settings_mode: "Mode:",
        settings_teams: "Teams 2×2",
        settings_ffa: "FFA",
        settings_start: "Start Game",
        settings_rules: "📖 Rules",
        settings_tutorial: "🎓 Tutorial",
        settings_about: "❤️ About",
        settings_lang: "Language / Язык",
        settings_dev: "Dev Mode",
        // Controls
        speed_name: "Speed:",
        theme_title: "Theme",
        // Hamburger
        hamburger_rules: "📖 Rules",
        hamburger_sound: "Sound",
        hamburger_speed: "Speed",
        hamburger_theme: "Theme",
        hamburger_keys: "⌨ Hotkeys",
        hamburger_log: "📋 Game Log",
        hamburger_lang: "🌐 Language",
        hamburger_menu: "Menu",
        // Herald / game
        herald_game_on: "Game on! {{ who }} goes first.",
        herald_roll: "{{ who }} rolls…",
        herald_no_move: "{{ who }}: rolled {{ a }} and {{ b }}. No moves — skip.",
        herald_wait_move: "{{ who }}: rolled {{ a }} and {{ b }}. Choose a move.",
        herald_ai_thinking: "{{ who }}: rolled {{ a }} and {{ b }}. Choosing a move…",
        herald_double: "{{ who }}: rolled {{ a }} and {{ b }}. Doubles — extra turn!",
        // Burn
        burn_double: "{{ who }}: can't play {{ n }} — doubles, reroll!",
        burn_pip: "{{ who }}: can't play {{ n }} — pip burns.",
        // Forced reply
        forced_reply: "{{ who }}: forced 6-pip reply after ransom.",
        forced_pick_msg: "{{ who }}: choose the forced 6-pip reply after ransom.",
        // Move notes
        note_capture: "{{ who }} captures a piece: {{ victim }}!",
        note_finish: "{{ who }}: all pieces home — finish!",
        note_ransom: "{{ who }}: piece ransomed.",
        note_enter: "piece entered.",
        note_moon_enter: "piece flies to the Moon!",
        note_moon_advance: "advancing on the Moon track.",
        note_moon_exit: "exiting the Moon.",
        note_prison_enter: "piece lands in Prison!",
        note_prison_release: "released from Prison.",
        note_home_enter: "piece enters Home!",
        note_home_advance: "piece advances deeper into Home.",
        // Side name
        side_human: "Player",
        side_ai: "AI",
        // Result
        result_team_wins: "Team {{ team }} wins! Game over.",
        result_full: "{{ who }} wins! Places: {{ places }}.",
        // Demo
        demo_reserve: "Reserve (start)",
        demo_moon_1: "16 pieces on Moon — field 1",
        demo_moon_3: "16 pieces on Moon — field 3",
        demo_moon_6: "16 pieces on Moon — field 6",
        demo_cell: "16 pieces on corner",
        demo_prison: "16 pieces in one Prison",
        demo_prison_stack: "Prison: same-color stacks",
        demo_captured: "12 pieces captured (max)",
        demo_homes: "Homes full",
        demo_anim: "▶ Animation: move and capture",
        demo_home_test: "🏠 Test: Home entry (click)",
        demo_complete: "Demo complete.",
        // Dev
        dev_title: "Dev mode: choose a scenario.",
        dev_sounds: "Sounds:",
        dev_back: "Settings",
        // Sound labels
        sound_dice: "🎲 Dice",
        sound_enter: "⬇ Enter",
        sound_capture: "💥 Capture",
        sound_prison_in: "🔒 To Prison",
        sound_prison_out: "🔓 From Prison",
        sound_moon: "🌙 Moon",
        sound_ransom: "💰 Ransom",
        sound_home: "🏠 Home",
        sound_win: "🏆 Win",
        // Game UI
        game_pause: "Pause",
        game_resume: "Resume",
        game_stop: "End Game",
        game_keys_title: "Hotkeys",
        game_keys_tab: "next piece",
        game_keys_1_2: "move with smaller / larger die",
        game_keys_3: "both dice on selected piece",
        game_keys_i: "enter piece from reserve",
        game_keys_r: "ransom captured piece",
        game_log_title: "Game Log",
        game_log_hint: "Click text to select all, then Ctrl/Cmd+C",
        game_log_close: "Close",
        // About page
        about_title: "About",
        about_p1: "This board game was known among MEPhI (Moscow Engineering Physics Institute, now NRNU MEPhI) students back in the 1970s as «Shesh-Besh», «Shish-Besh», or just «Shishka». My father played it with his classmates.",
        about_p2: "In the 1990s I was a kid, and one day my father and I bought a sheet of drawing paper at a bookstore and he drew the board on it. We would play in the evenings, sitting on the rug. His school and college friends would join us. It was wonderful.",
        about_p3: "Remembering those moments with warmth, I decided to recreate the game on a computer.",
        about_p4: "I couldn't find any mention of this variant online; I only found a similar game called «Shesh-Besh» with a cross-shaped board and no Moon or Prison.",
        // Rules page
        rules_title: "Shesh-Besh — Rules",
        rules_lead: "Unique backgammon variant. Played by two (opposite sides) or four; each player owns one side of the square and its Home. Four players can play as teams 2×2 (allies are opposite sides) or each for themselves (FFA).",
        rules_goal_title: "Goal",
        rules_goal_text: "Move all 4 pieces a full lap around the board (counter-clockwise) and bring them into your Home. Enemy pieces cannot enter your Home. In 2-player mode, first to fill Home wins. In teams 2×2, victory when both team sides have all pieces home. In FFA, the game continues until all but one have finished (last place loses).",
        rules_first_title: "First Move",
        rules_first_text: "Active sides take turns rolling; whoever rolls 6 first goes first.",
        rules_board_title: "Board",
        rules_board_l1: "Square; each of the 4 sides has 19 cells (corners shared by two sides). Counter-clockwise.",
        rules_board_l2: "In the middle of each side is the Home — 4 cells going inward.",
        rules_board_l3: "All pieces start in reserve at their Home and enter the game by rolling 6.",
        rules_move_title: "Move",
        rules_move_l1: "A turn consists of rolling two dice. Values can be assigned to two different pieces (one die each) or combined on one piece (\"in one swing\").",
        rules_move_l2: "«Rolling a number» always means the value on a single die, not the sum.",
        rules_move_l3: "Dice can only be combined when moving on the perimeter. Special actions (entry, ransom, Moon, Prison, Home) require exactly one die of the needed value.",
        rules_move_l4: "Entering a piece: roll 6. Cannot place a second piece of your own on the entry point; an enemy piece there can be captured.",
        rules_move_l5: "Doubles grant an extra full turn.",
        rules_move_l6: "Maximum pip rule: choose the option that uses the most pips (ideally all).",
        rules_move_l7: "Cannot pass through occupied cells — except corners (can pass through an occupied corner). Cannot step over own or enemy pieces on the path.",
        rules_special_title: "Special Cells",
        rules_special_l1: "Moon (2nd cell from corner) — shortcut. Piece flies to the inner track fields 1·3·6: from «1» to «3», from «3» to «6», from «6» back to the board (2nd cell from the next corner). If an enemy piece stands at the exit, it is captured. The Moon is completely safe (both entry and track).",
        rules_special_l2: "Prison (4th cell from corner) — isolates the piece: can only leave by rolling 4 (piece is freed and stays in place, no advancement). Good for blocking enemies. A piece enters Prison only if the Prison cell is the final stop; if merely stepping over it (combined move or larger value), Prison does not trigger.",
        rules_special_l3: "Corners — shared cells; pieces do not capture each other here, and occupied corners can be passed through.",
        rules_capture_title: "Capture, Prisoner, and Ransom",
        rules_capture_l1: "Land on a cell with an enemy piece — you capture it (it becomes your prisoner). In teams 2×2, allies do not capture each other.",
        rules_capture_l2: "No captures on corners, Moon, or Prison.",
        rules_capture_l3: "To return a captured piece, roll 6 (ransom). The opponent cannot refuse — they must make a reply move of 6 cells (if a legal 6-pip move exists; otherwise skip). After that, another 6 is needed to re-enter the piece.",
        rules_home_title: "Home",
        rules_home_text: "Entering Home — exactly by the die value, one piece per cell; cannot jump over occupied Home cells (but a piece already in Home can move deeper, freeing space). Going past Home is illegal. A second lap is possible via the Moon: your own Moon sits right by your Home, and the piece exits at the start of the lap — forcing another full lap.",
        // Tutorial
        lesson_title_1: "Goal and Entry",
        lesson_text_1: "Each player has 4 pieces in reserve; the goal is to go around the board counter-clockwise and gather all in your Home. Rolled 6 and 5: with 6 the piece enters the board, then with 5 it reaches Prison. Click the piece, then the cell (one die at a time), or ▶.",
        lesson_title_2: "Prison and Moon",
        lesson_text_2: "Prison holds the piece: can only leave by rolling 4 — and you did! Then the remaining 6 takes the piece further, landing on the Moon. Make both sub-moves.",
        lesson_title_3: "Moon",
        lesson_text_3: "The Moon is a short safe path through fields 1·3·6 (cannot be captured). Rolled 1 — advance from field «1» to «3». The second die (2) is not played: on the Moon you need the exact value. Make your move.",
        lesson_title_4: "Moon Track",
        lesson_text_4: "Rolled 3 — advance from field «3» to «6». You still need to roll 6 to exit the Moon.",
        lesson_title_5: "Exiting the Moon",
        lesson_text_5: "With 6 the piece exits the Moon back to the board, noticeably closer to Home. An enemy piece lies ahead.",
        lesson_title_6: "Capture",
        lesson_text_6: "Land on a cell with an enemy piece — you capture it! The prisoner goes near your Home (with a red outline). No capturing on corners, Moon, or Prison.",
        lesson_title_7: "Prisoner and Ransom",
        lesson_text_7: "To get a captured piece back, its owner rolls 6 — it returns to reserve (ransom). The opponent immediately ransoms their piece (it flies to their reserve). Then the captor must immediately move 6 cells: choose which piece of yours — click the piece, then the highlighted cell.",
        lesson_title_8: "Home and Victory",
        lesson_text_8: "Reaching Home, the piece enters exactly by the die — one per cell; cannot jump over occupied Home cells (but can move deeper). Enemy pieces cannot enter Home. Bring this piece home — all 4 pieces home, and you win!",
        // Tutorial hints
        tutorial_hint_roll: "🎲 Rolling…",
        tutorial_hint_opp_roll: "🎲 Opponent rolling…",
        tutorial_hint_move: "👆 Make a move: click a piece, then the highlighted cell. Or press ▶.",
        tutorial_hint_ransom: "👆 Choose which piece to make the forced 6-pip move: click the piece, then its cell.",
        tutorial_lesson: "Lesson",
        tutorial_back: "Back to menu",
        tutorial_prev: "◀ Back",
        tutorial_next: "Next",
        // Home test
        home_test_herald: "Home entry test: the gate is a regular perimeter cell where you can stop (Step); entering Home is a separate move from the gate inward.",
    },
}
mod ai_worker;

mod app;

mod controls;
mod demo;
mod geom;
mod lessons;
mod model;
mod moves_ui;
mod settings;
mod util;
mod view;

use app::App;

fn main() {
    console_error_panic_hook::set_once();
    leptos::mount::mount_to_body(App);
}
